---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una nota periodística en un diario impreso
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una nota periodística en la página web de ese mismo diario
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una foto en tu red social favorita
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una foto en la galería de fotos de tu celular
  checked: false
name: La famosa Web
