---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Navegar por páginas web
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Enviar correos electrónicos (_emails_)
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Realizar videollamadas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Chatear
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas las anteriores
  checked: true
name: Los usos de Internet
