---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Computadoras gigantes que ocupan edificios enteros
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Computadoras comunes como las que se pueden encontrar en una casa
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mini computadoras que entran en cualquier bolsillo
  checked: false
name: Servidor a sus servicios
