---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: GET
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: POST
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: PUT
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: DELETE
  checked: false
name: Algo más metódico
