---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El envío de una carta de un país a otro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El ingreso a un álbum en la página de espótifai
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El envío de un mensaje de texto de un celular a otro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La búsqueda de una persona en una red social
  checked: true
name: Ceremonial y protocolo
