---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`https`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`github.com`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`/mumuki`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`/mumuki/mumuki-laboratory/blob/master/public/logo-alt-large.png`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`https://github.com/mumuki/mumuki-laboratory/blob/master/public/logo-alt-large.png`"
  checked: false
name: Identificación por favor
